### ISSUE TITLE
Fix dApp footer

### ISSUE THREAD

**Issue by Agupane** [thebadge/thebadge-dapp#156]
## Description
- The footer should be clickable links instead of plain text, the cookies should redirect to the cookies section of the web. TheBadge.xyz should redirect to the web

![image.png](https://images.zenhubusercontent.com/5dc5adeaf1b75b0001fb811c/5b1124e4-206b-4e69-93a3-a430bf28dc1e)

- TheBadge logo should redirect to the web
![image.png](https://images.zenhubusercontent.com/5dc5adeaf1b75b0001fb811c/dae9bb65-ddaa-4c11-9944-7fe40dd22809)

**Comment by FedeMadoery** [comment]
Cookies thing need to be disabled with env var, lets do it in that way for now
