### ISSUE TITLE
Badge explorer mint button

### ISSUE THREAD

**Issue by agulombardi** [thebadge/thebadge-dapp#243]
When trying to click the mint button on the badge image, it does nothing. I am forced to go to the mint on the right.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3789a76e3fe0f9ff79a41336b997b4da56d0a3a7/image.png)

**Comment by Agupane** [comment]
Closing this as its a duplicate of #334
