### ISSUE TITLE
bug - home: The redirection to the creator profile is not working

### ISSUE THREAD

**Issue by Agupane** [thebadge/thebadge-dapp#76]
## Description
- On the badges types explorer if you click on the following link to go and check the creator's profile, it should point to the following URL: `https://staging-dapp.thebadge.xyz/profile/<creatorAddress>`, but it's redirecting to the following address: `https://staging-dapp.thebadge.xyz/badge/%22https:/app.thebadge.xyz%22/profile/<creatorAddress>`

**Comment by FedeMadoery** [comment]
This bug is something to fix on Vercel. It won't need a PR.

**Comment by FedeMadoery** [comment]
Done, we will need to retest it when we do a new deployment, just in case.
